# Generated by Django 3.1.5 on 2021-01-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
